### ISSUE TITLE
WYSIWYG in repeaters

### ISSUE THREAD

**Issue by joelworsham** [realbig/rbm-field-helpers#4]
![](https://cdn.meme.am/instances/14941553.jpg)

**Comment by d4mation** [comment]
Turns out I was incredibly close to making the "Text" tab work properly when I made that PR.

From here all that needs to be fixed up are the Row deletion events for re-incrementation and adding a conditional for the `teeny` setting. I'm thinking a Class name check is likely the best way to handle it.

**Comment by joelworsham** [comment]
🎉

**Comment by d4mation** [comment]
As mentioned in #8, there's still that pretty glaring visual bug. Once that's figured out, I'd say this Issue is good to be closed and the changes to be merged into Master :tada:
